pipeline {
    agent any
    environment {
        PYTHONPATH = 'Module_4_TASK2_PYTEST'
    }
    stages {      
        stage('run tests') {
            steps {
                sh 'Module_4_TASK2_PYTEST'
            }
        }
    }
}
