pipeline {
    agent any
    environment {
        PYTHONPATH = 'Module_4_TASK2_PYTEST'
    }
    stages {
            stage('Test') {
                steps {
                    echo 'Hello World ...'
                }

    }
}
